### ISSUE TITLE
Error running `npm install`

### ISSUE THREAD

**Issue by Gene-Dana** [danmindru/responsive-html-email-signature#105]
This is the best looking signature I've seen so far, and I'd really like to run the project ! 

```
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/geneyllanes/development/GitHub/email-signature/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.3.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/17.5.0/bin/node" "/Users/geneyllanes/development/GitHub/email-signature/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/geneyllanes/development/GitHub/email-signature/node_modules/node-sass
npm ERR! gyp ERR! node -v v17.5.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1
```

I get this error every time I go to run ! I understand the project is 4 yrs old, and I looked to even see it working on the branch from last year, although this is the same answer

Am I doing something wrong here? I'm using the Apple M1 Pro 14in, and I have Node 8.4.1

**Comment by danmindru** [comment]
Hello @Gene-Dana, sorry for the inconvenience.
Officially, the project supports node v10+. 
With each merge builds are created for [node v10-v14](https://github.com/danmindru/responsive-html-email-signature/actions/runs/1828471273)  on mac, so upgrading node to v10 or higher should get you going.
Alternatively, you can use `nvm` on mac to run multiple node versions at once. See https://github.com/nvm-sh/nvm

**Comment by Gene-Dana** [comment]
Wow ! I didn't realize I installed such an old version ! Thanks :D

**Comment by Gene-Dana** [comment]
@danmindru I was mistaken ! That was the version of NPM. I'm running Node 17. Just tried again from a fresh install of node and still get the gyp error ! 

I really want to use this email signature lol..

**Comment by bilazor4ik** [comment]
> @danmindru I was mistaken ! That was the version of NPM. I'm running Node 17. Just tried again from a fresh install of node and still get the gyp error !
> 
> I really want to use this email signature !

Downgrade your version of Node to 14.19.0

It helped me

**Comment by danmindru** [comment]
Thanks for the extra info! Seems like the newer node introduces a breaking change in one of the dependencies.
I'll try to get it sorted out soon and add support for node v17 (and hopefully higher)

**Comment by danmindru** [comment]
Added support for node v17 in v6.1.1 (https://github.com/danmindru/responsive-html-email-signature/pull/106)
Thanks again for pointing out the issue!
