### ISSUE TITLE
OS X High Sierra setup instructions 

### ISSUE THREAD

**Issue by reederz** [danmindru/responsive-html-email-signature#36]
Even though the current OS X setup instructions are super sketchy, they do work. Or at least they used to. Meet [High Sierra](https://www.apple.com/macos/high-sierra/) - the nightmare of responsive html signatures.

Jokes aside, editing signature on disk with email client closed does fuck all because once you open the client, the signature gets overwritten. Could it be related to the new filesystem they launched?

CC: @danmindru

**Comment by reederz** [comment]
Dan, can you see if you can reproduce this when you have a moment? No rush. It could be that it's specific to Lars' environment (I saw the behaviour on his laptop myself).

**Comment by danmindru** [comment]
I don't have the option to update yet, will try when it pops up

**Comment by reederz** [comment]
@danmindru I was poking around today and found this https://www.youtube.com/watch?v=x-pATsvrQQc . Then I realised that those instructions can be adapted to our signatures too. Here's roughly how it goes:
- copy html
- publish it as a webpage: local, on server, doesn't matter - as long as you can open it with browser.
- open the webpage in chrome browser
- cmd + A; cmd + C (i.e. copy the contents)
- create new signature in email app
- uncheck "Always match my default font" checkbox below the signature editor
- paste the copied webpage contents
- you're good to go!

This worked perfectly for Lars. Let me know if you see any problems with this approach.

**Comment by reederz** [comment]
If this approach is fine with you, you or I could easily setup a CI workflow to automatically publish signatures as webpages E.g. on github pages or one of our servers.

**Comment by danmindru** [comment]
yeah it's an alternative way, BUT the responsive styles (`<style>` block in `<head>`) are going to be lost during the process. 
That's why we went through all the trouble before. When editing the source directly we could be sure everything in `<head>` makes it in the signature.

**Comment by reederz** [comment]
Bugger... Well, it will do for now as it's better than nothing.

**Comment by reederz** [comment]
For what it's worth, responsiveness works on:
-  thunderbird, when resizing the window
- android email client
- gmail webclient
- tutanota.com web client
- tutanota.com mobile client

Can't test outlook though. Is that where it might not work, you think?

**Comment by danmindru** [comment]
I'd test it on a mobile device. The email content should fit whatever size the mobile device viewport is (both portrait and landscape) without having to scroll horizontally.

**Comment by reederz** [comment]
Check your gmail or @fadeit.dk email when you have time - I've sent you a test.
