### ISSUE TITLE
Get this to work in Gmail??

### ISSUE THREAD

**Issue by jeanverster** [danmindru/responsive-html-email-signature#40]
Hi there, please provide some info about your enviornment before submiting this issue:
- device        : Macbook Pro
- OS            : Sierra
- email client  : Gmail
- node version  : 7.8.0
- npm version   : 5.0.1
- error message : None

hi,

I am not encountering any errors with the package itself, I am just having a really hard time getting it to work with gmail.. The only way I seem to be able to insert the signature is to export as html, open in browser, then copy paste all that into the signature box - but this obviously doesn't copy the <head> / <style> tag therein! I've also noticed that gmail does apparently support media queries nowadays, but having a tough time getting this to work in the signature! 

Any help would be greatly appreciated.

**Comment by Bewinxed** [comment]
Facing this issue as well, apparently you can copy paste it but the problem is the signature this code produces has way too many characters that passes gmail signature limit.

**Comment by danmindru** [comment]
A hint here: try to use absolute URLs for images (`http://...`) instead of a local path. This way the image doesn't get inlined in the resulting HTML and you have a better chance to fit it in Gmail.
