### ISSUE TITLE
Gulp error

### ISSUE THREAD

**Issue by thallesmarchetti** [danmindru/responsive-html-email-signature#46]
Hi there, please provide some info about your enviornment before submiting this issue:
- device        : MacBook Pro
- OS            :  macOS High Sierra
- email client  : linkmarchetti@gmail.com
- node version  : v10.9.0
- npm version   : 6.2.0
- error message : 
![screen shot 2018-08-20 at 19 08 00](https://user-images.githubusercontent.com/29786923/44369327-63c53980-a4ac-11e8-971c-e69abaa5c701.png)

![screen shot 2018-08-20 at 19 00 07](https://user-images.githubusercontent.com/29786923/44369124-acc8be00-a4ab-11e8-9c8e-4fa0f488b455.png)

**Comment by danmindru** [comment]
Hi there, have you tried installing dependencies with npm?
It might be a good idea to nuke your node_modules and see if the same happens with npm install.

We haven't tested on node 10+ yet, so that might also be the cause here. Did you try the same with an older version of node by chance?

**Comment by thallesmarchetti** [comment]
It works pretty well. 

Thanks for your help!
