### ISSUE TITLE
Use as Gmail signature, but the image doesn't appear

### ISSUE THREAD

**Issue by spinoutofcontrol** [danmindru/responsive-html-email-signature#53]
Hi there, please provide some info about your enviornment before submiting this issue:
- device        : MacBook Pro (15-inch, 2016)
- OS            : macOS High Sierra Version 10.13.6
- email client  : Gmail
- node version  : v10.13.0
- npm version   : 6.4.1
- error message 

Thank you for your work.
I have one question for you.
I tried to copy and paste it to use as a Gmail signature, but the image doesn't appear, so is there a solution?

**Comment by danmindru** [comment]
Hi there,

Did you try to use absolute URLs for images (`http://...`) instead of a local path? 
I think inlining images with base64 might be problematic in Gmail.

**Comment by NoWorries** [comment]
Base64 issues arise because gmail limits characters in the custom html. Best bet is to use a hosted image with absolute URL as @danmindru suggested

**Comment by ch-choi** [comment]
@danmindru 
I try upload image at Google Drive. And use Google Drive image URL instead base64. But no image appears.

**Comment by danmindru** [comment]
Hi @ch-choi, can you open a new issue with your configuration? 
Thanks!
