### ISSUE TITLE
npm installation issue

### ISSUE THREAD

**Issue by cankaya07** [danmindru/responsive-html-email-signature#76]
Hi there, please provide some info about your enviornment before submiting this issue:
- device        : MacBook Pro 2019
- OS            : macOS catalina
- email client  : ---
- node version  : v10.15
- npm version   : 6.9.0
- error message :
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/es-abstract/-/es-abstract-1.14.0.tgz
npm ERR! 404
npm ERR! 404  'es-abstract@1.14.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'responsive-html-email-signature'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cankaya/.npm/_logs/2020-02-12T11_59_42_090Z-debug.log

found the package from this url.

http://staging.araqne.org/archiva/repository/npm_proxy/es-abstract/-/es-abstract-1.14.0.tgz

**Comment by danmindru** [comment]
Hi there @cankaya07.
Thanks for reporting the issue. I've updated the dependencies and so far, things are looking OK.
It should build ok on latest mac versions on node 9,10,11,12 & 13 as you can see here:
https://github.com/danmindru/responsive-html-email-signature/actions/runs/43978714

Let me know if you are still experiencing any problems.
Best,
Dan
