### ISSUE TITLE
NPM install returns SyntaxError: missing ) after argument List

### ISSUE THREAD

**Issue by nobels** [danmindru/responsive-html-email-signature#81]
Hi there, please provide some info about your enviornment before submiting this issue:
- OS            : Windows 10
- node version  : v12.18.0
- npm version   : 6.14.5
- error message : SyntaxError: missing ) after argument List

I removed all the modules and did npm install again.
After npm start I still get the error.
![sshot-681](https://user-images.githubusercontent.com/4178473/84001343-ac423580-a966-11ea-9592-aa40ddda6569.jpg)

I did the same thing on my macbook with Catalina v10.15.4 -> and there it works (with npm and node equal in versions)

this is the content from the log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\XXX\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle responsive-html-email-signature@6.0.0~prestart: responsive-html-email-signature@6.0.0
6 info lifecycle responsive-html-email-signature@6.0.0~start: responsive-html-email-signature@6.0.0
7 verbose lifecycle responsive-html-email-signature@6.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle responsive-html-email-signature@6.0.0~start: PATH: C:\Users\XXX\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Projects\Responsive email signature\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Do3think\DVP2\;C:\Program Files (x86)\Do3think\DVP2 x64\;C:\APP\CLIENT\XXX\PRODUCT\12.1.0\CLIENT_1;C:\APP\CLIENT\XXX\PRODUCT\12.1.0\CLIENT_1\BIN;C:\PROGRAM FILES (X86)\COMMON FILES\ORACLE\JAVA\JAVAPATH;C:\PROGRAMDATA\ORACLE\JAVA\JAVAPATH;C:\PROGRAM FILES\MICROSOFT MPI\BIN\;C:\PROGRAM FILES\DELL\DW WLAN CARD;C:\WINDOWS\SYSTEM32;C:\WINDOWS;C:\WINDOWS\SYSTEM32\WBEM;C:\WINDOWS\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM FILES (X86)\NVIDIA CORPORATION\PHYSX\COMMON;C:\PROGRAMDATA\CHOCOLATEY\BIN;C:\PROGRAM FILES (X86)\YARN\BIN\;C:\PROGRAM FILES (X86)\SUBVERSION\BIN;C:\PROGRAM FILES\DOTNET\;C:\PROGRAM FILES\MICROSOFT SQL SERVER\130\TOOLS\BINN\;C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\CLIENT SDK\ODBC\130\TOOLS\BINN\;C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\140\TOOLS\BINN\;C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\140\DTS\BINN\;C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\140\TOOLS\BINN\MANAGEMENTSTUDIO\;C:\WINDOWS\SYSTEM32\OPENSSH\;C:\PROGRAM FILES\MICROSOFT\WEB PLATFORM INSTALLER\;C:\PROGRAM FILES\MICROSOFT VS CODE\BIN;C:\PROGRAM FILES\GIT\CMD;;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\IBM\Client Access\Shared;C:\Program Files (x86)\IBM\Client Access\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Kodak\Document Imaging\kds_i11xx\Smart Touch\;C:\Program Files\nodejs\;C:\Ruby27-x64\bin;C:\PROGRAM F;C:\Users\XXX\.dotnet\tools;C:\Users\XXX\AppData\Roaming\npm
9 verbose lifecycle responsive-html-email-signature@6.0.0~start: CWD: C:\Projects\Responsive email signature
10 silly lifecycle responsive-html-email-signature@6.0.0~start: Args: [ '/d /s /c', 'node ./node_modules/.bin/gulp' ]
11 silly lifecycle responsive-html-email-signature@6.0.0~start: Returned: code: 1  signal: null
12 info lifecycle responsive-html-email-signature@6.0.0~start: Failed to exec start script
13 verbose stack Error: responsive-html-email-signature@6.0.0 start: `node ./node_modules/.bin/gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid responsive-html-email-signature@6.0.0
15 verbose cwd C:\Projects\Responsive email signature
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\XXX\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.18.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error responsive-html-email-signature@6.0.0 start: `node ./node_modules/.bin/gulp`
22 error Exit status 1
23 error Failed at the responsive-html-email-signature@6.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by danmindru** [comment]
Thanks @nobels! 
I'll take a look at it in windows :)

**Comment by danmindru** [comment]
Alright, should be solved now.
Test buids seem to also agree :) 

Let me know if you have any other issues
https://github.com/danmindru/responsive-html-email-signature/actions/runs/130815085

Cheers,
Dan
