### ISSUE TITLE
after adding values in conf.json -> I need to restart npm to have affect.

### ISSUE THREAD

**Issue by nobels** [danmindru/responsive-html-email-signature#84]
- OS            : Windows 10
- email client  :
- node version  : v12.18.0
- npm version   : 6.14.5
- error message :  none -> result in dist folder contains "undefined" text as value. 

step 1: add new value in conf.json file example _"test": "Custom text",_
step 2: use the value inside the html inside template. and save it.
step 3: check the result in "dist" folder. -> you will see that your new added value is not there.
step 4: Ctrl+C to terminate batch job.
step 5: start NPM -> then it goes well in generation.  -> check again and the result is there.

**Comment by danmindru** [comment]
Thanks for the report!
Sounds like a bug to me, although conf files should be 'watched' according to [gulpfile.js#45](https://github.com/danmindru/responsive-html-email-signature/blob/master/gulpfile.js#L45)

I'll try and take a look at it.
Cheers,
Dan
