### ISSUE TITLE
Issue with "Generating multiple emails from the same config ".

### ISSUE THREAD

**Issue by tnchuntic** [danmindru/responsive-html-email-signature#97]
Hi there, please provide some info about your enviornment before submiting this issue:
- device        :
- OS            : MAC
- email client  : N/A
- node version  :  12.14.1
- npm version   : 7.11.2
- error message :  
Plumber found unhandled error: Error: Callback called multiple times.

Also I am trying to generate multiple emails signatures using the array config.

[
    {
        "id": "light",
        "signature": "Cheers,",
        "name": "Kaaaa Jaaaaa",
        "pronounce": "(she/her)",
        "role": "Office Coordinator",
        "company": "LHA",
        "welcome": "Hi there,",
        "introParagraph": "<strong>The LHA respectfully acknowledges ....</strong> – the land of the ... and passes on respect to their Elders past and present, future and emerging.",
        "contactPhone": "0000 000 000",
        "contactMobile": "000 0000 0000",
        "contactMail": "info@domain.com.au",
        "contactSecondary": "Address",
        "logoUrl": "logo url",
        "logoAlt": "lha",
        "website": "https://www.domain.comau/"
    }, {
        "id": "light",
        "signature": "Cheers,",
        "name": "Raaaa Jaaaaa",
        "pronounce": "(she/her)",
        "role": "Office Coordinator",
        "company": "LHA",
        "welcome": "Hi there,",
        "introParagraph": "<strong>The LHA respectfully acknowledges ....</strong> – the land of the ... and passes on respect to their Elders past and present, future and emerging.",
        "contactPhone": "0000 000 000",
        "contactMobile": "000 0000 0000",
        "contactMail": "info@domain.com.au",
        "contactSecondary": "Address",
        "logoUrl": "logo url",
        "logoAlt": "lha",
        "website": "https://www.domain.comau/"
    }, {
        "id": "light",
        "signature": "Cheers,",
        "name": "Laaaa Jaaaaa",
        "pronounce": "(she/her)",
        "role": "Officer",
        "company": "LHA",
        "welcome": "Hi there,",
        "introParagraph": "<strong>The LHA respectfully acknowledges ....</strong> – the land of the ... and passes on respect to their Elders past and present, future and emerging.",
        "contactPhone": "0000 000 000",
        "contactMobile": "000 0000 0000",
        "contactMail": "info@domain.com.au",
        "contactSecondary": "Address",
        "logoUrl": "logo url",
        "logoAlt": "lha",
        "website": "https://www.domain.comau/"
    }
]

**Comment by danmindru** [comment]
hi there @tnchuntic,

Might it be because the logoUrl is not valid?
Could you try adding that? It could be local `"logoUrl": "/assets/light.png",` or the url to any image on the web :)

**Comment by kinglouie** [comment]
the issue is that you use the same `id` for all three entries.
