### ISSUE TITLE
Fail with bad image urls 

### ISSUE THREAD

**Issue by danmindru** [danmindru/responsive-html-email-signature#98]
Invalid urls should fail with a nice message

**Comment by anujpunjani** [comment]
Hi, as a beginner, I would like to work on this issue. Please correct me if I am wrong, as I understand, image URLs inserted in email content could be broken and we should check if it is failing to load the image first and if yes then we should replace it with the nice message?

**Comment by danmindru** [comment]
Hi @anujpunjani, thanks for taking the time - really appreciate it 🙂

Exactly, if the url format is incorrect, an error message should be displayed so people don’t waste time debugging

**Comment by danmindru** [comment]
A simple version would be to just check if the url has a correct format.
A more advanced one would be to actually try to get that image (http GET) and see if the response is 200 and it is actually an image

**Comment by anujpunjani** [comment]
Thanks for the reply @danmindru, Could you please assign me to the issue? Or If I raise a PR for this issue that would do that automatically?
Also, if you have any current screenshots of this failed scenario, could you please share it and the code reference to provide a jump start?

**Comment by danmindru** [comment]
Fixed in #100 🎉
